---
output:
  md_document:
    variant: markdown_github
bibliography: refs.bib  
---

# Crane Trachea

## Cryptic sexual size dimorphism

Cryptic size dimorphism (CSDI) is a bit of a strange term. How can size dimorphism be cryptic. If we can say sizes are different doesn't that imply we (humans) can detect the difference. After all cryptic as a concept in biology largely relies on the human frame of reference. We cannot tell what differences other animals can detect. No they do not all look/smell/sound/chemically signal the same. 

From a human standpoint, as if I could speak to any other, CSDI often refers to allometric scaling differences between the sexes, where one sexes body part is larger than expected given body size.

Here we extend a line of inquiry originating with @fitch1999acoustic, and extended to examine evolutionary trade offs in @jones2014migrate. They found that some birds, crane species in particular, exhibit a looping of the trachae (tracheal elongation). It is hypothesized that the proportionally longer trachea act to signal larger body size through acoustic modulation of formant spacing @fitch1999acoustic, @jones2012utility. This can compensate for constraints on body size by like long migratory paths @jones2014migrate. Here we grow the dataset from @jones2014migrate to ask if the intraspecific <u>cryptic size dimorphism<u> they found in Sandhill Cranes is present as another layer divergence between subspecies. Here we look for, quantify, and evaluate mechanisms of cryptic <u>sexual<u> size dimorphism between subspecies.

# References